### ISSUE TITLE
Login name for Octance

### ISSUE THREAD

**Issue by johnrauser** [panama69/HPE-ALM-Octane-Docker#1]
I have my container up and running and I'm looking at the Octane login page, however I cannot figure out the name to log in with. I know what I set the ADMIN_PASSWORD to, but I don't know what account name to use it with. Please advise, thanks

**Comment by panama69** [comment]
I suggest  you use the instructions found on https://hpln.hpe.com/contentoffering/hpe-alm-octane-docker-container-technology-preview for a couple of reasons:
1)	The main reason is it makes use of the latest version of ALM Octane 12.53.16.
2)	Since this is based on an older version, I won’t be maintaining it.

The project you are referencing below was with ALM Octane 12.53.8.

But to answer your question, the login name is ‘sa@nga’
You can find the other default settings that were used in the https://github.com/panama69/HPE-ALM-Octane-Docker/blob/master/12.53.08/setup.xml
